name: first workflow
on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Node.js dependencies
        working-directory: frontend/library
        run: npm ci
      - name: Build Node.js project
        working-directory: frontend/library
        run: npm run build
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "backend/requirements.txt"

      